### ISSUE TITLE
Installation starts failing after update to 5.2.0

### ISSUE THREAD

**Issue by miguelgf** [sendwithus/sendwithus_python#76]
### Client version
5.2.0

### Expected behaviour
The installation works

### Actual behaviour
The installation fails with this error:

```
Collecting sendwithus==5.2.0
  Using cached sendwithus-5.2.0.tar.gz (14 kB)


:stderr:     ERROR: Command errored out with exit status 1:

     command: /var/www/virtualhosts/miguelgf/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/miguelgf/.pip/build/sendwithus/setup.py'"'"'; __file__='"'"'/home/miguelgf/.pip/build/sendwithus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /home/miguelgf/.pip/build/sendwithus/pip-egg-info

         cwd: /home/miguelgf/.pip/build/sendwithus/

    Complete output (7 lines):

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/miguelgf/.pip/build/sendwithus/setup.py", line 5, in <module>
        long_description = fp.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7973: ordinal not in range(128)
```

### Steps to reproduce
- `pip install sendwithus==5.2.0`

Regards

**Comment by demoore** [comment]
Interesting. I can't seem to reproduce this on my machine, but I've pushed a branch to make the encoding explicit. Before I merge any changes, can you please test this by running the below in your virtualenv
```
pip install git+https://github.com/sendwithus/sendwithus_python@use-explicit-encoding
```

If it comes to it, we can remove non-ASCII characters from the README.

Thanks!

**Comment by miguelgf** [comment]
Great! it seems to work properly now

```sh
$ pip install git+https://github.com/sendwithus/sendwithus_python@use-explicit-encoding
Collecting git+https://github.com/sendwithus/sendwithus_python@use-explicit-encoding
  Cloning https://github.com/sendwithus/sendwithus_python (to revision use-explicit-encoding) to /tmp/pip-req-build-1a94abxg
  Running command git clone -q https://github.com/sendwithus/sendwithus_python /tmp/pip-req-build-1a94abxg
  Running command git checkout -b use-explicit-encoding --track origin/use-explicit-encoding
  Switched to a new branch 'use-explicit-encoding'
  Branch 'use-explicit-encoding' set up to track remote branch 'use-explicit-encoding' from 'origin'.
Requirement already satisfied: requests>=2.0.0 in /var/www/virtualhosts/miguel/venv/lib/python3.6/site-packages (from sendwithus==5.2.0) (2.23.0)
Requirement already satisfied: six>=1.9.0 in /var/www/virtualhosts/miguel/venv/lib/python3.6/site-packages (from sendwithus==5.2.0) (1.14.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests>=2.0.0->sendwithus==5.2.0) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests>=2.0.0->sendwithus==5.2.0) (2.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /var/www/virtualhosts/miguel/venv/lib/python3.6/site-packages (from requests>=2.0.0->sendwithus==5.2.0) (1.24.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests>=2.0.0->sendwithus==5.2.0) (2018.1.18)
Building wheels for collected packages: sendwithus
  Building wheel for sendwithus (setup.py) ... done
  Created wheel for sendwithus: filename=sendwithus-5.2.0-py3-none-any.whl size=14694 sha256=84eceb4c3aac41d7624c1115e7c9860eb4e6cde307b10ca26340620673f0c4d5
  Stored in directory: /tmp/pip-ephem-wheel-cache-rurucb6l/wheels/9d/9b/8d/79dcc6662c04bbebe76257280084a26d1eea7bdbd543b6f868
Successfully built sendwithus
Installing collected packages: sendwithus
  Attempting uninstall: sendwithus
    Found existing installation: sendwithus 5.1.0
    Uninstalling sendwithus-5.1.0:
      Successfully uninstalled sendwithus-5.1.0
Successfully installed sendwithus-5.2.0
```

**Comment by demoore** [comment]
Thanks so much @miguelgf! I really appreciate you trying it out. There's a new release (5.2.1) on PyPi now with the changes.
